spring:
  datasource:
    url: jdbc:h2:mem:indexdb
    driverClassName: org.h2.Driver
    username: rbc-user
    password: rbc-pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
   console:
     enabled: true